In [9]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[2, 0], [1, 3]])

print(A + B)  # Matrix addition
print(A * B)  # Element-wise multiplication
print(np.matmul(A, B))  # Matrix multiplication
print(np.linalg.inv(A))  # Inverse of A


[[3 2]
 [4 7]]
[[ 2  0]
 [ 3 12]]
[[ 4  6]
 [10 12]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [10]:
arr = np.array([10, 20, 5, 40, 50])

print(np.min(arr))  # Minimum
print(np.max(arr))  # Maximum
print(np.sum(arr))  # Sum of elements


5
50
125


In [11]:
arr = np.linspace(0, 10, 5)  # 5 equally spaced values between 0 and 10
print(arr)


[ 0.   2.5  5.   7.5 10. ]


In [12]:
arr = np.array([10, 5, 8, 3, 2])
sorted_arr = np.sort(arr)

print(sorted_arr)


[ 2  3  5  8 10]
